apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  ports:
  - port: {{ .Values.service.vprodb.port }}
    targetPort: vprodb-port
    protocol: TCP
  selector:
    app: vprodb
  type: ClusterIP
