apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  ports:
  - port: {{ .Values.service.vpromc.port }}
    targetPort: vpromc-port
    protocol: TCP
  selector:
    app: vpromc
  type: ClusterIP
