apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
  labels:
    app: vpromc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vpromc
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
      - name: vpromc
        image: {{ .Values.image.vpromc }}
        ports:
        - name: vpromc-port
          containerPort: {{ .Values.service.vpromc.port }}
