apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels:
    app: vpromq01
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vpromq01
  template:
    metadata:
      labels:
        app: vpromq01
    spec:
      containers:
      - name: vpromq01
        image: {{ .Values.image.vpromq01 }}
        ports:
        - name: vpromq01-port
          containerPort: {{ .Values.service.vpromq01.port }}
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: rmq-pass
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rmq.defaultUser | quote }}
